trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        choco install bazel python
        bazel build --compilation_mode=opt //:dist