trigger:
- master

pool:
  vmImage: 'windows-2019'


- powershell: |
    Invoke-WebRequest -OutFile bazel.exe https://github.com/bazelbuild/bazel/releases/download/2.1.0/bazel-2.1.0-windows-x86_64.exe
    bazel.exe build //:dist
  displayName: 'build'
