trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
  - task: CmdLine@2
    inputs:
      script: |
        set
        choco install bazel --no-progress
        bazel build -s --python_path=%PYTHON_HOME% --compilation_mode=opt //:dist