pool:
  vmImage: 'windows-2019'

steps:
  - task: CmdLine@2
    inputs:
      script: |
        set
        set PATH=%PATH%;%PYTHON_HOME%
        echo %PATH%
        python3 -c print(1234)
        choco install bazel --no-progress
        bazel build -s --python_path=%PYTHON_HOME% --compilation_mode=opt //:dist